DROP TABLE IF EXISTS programs CASCADE;
DROP TABLE IF EXISTS specimens CASCADE;

CREATE TABLE programs
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    program_number VARCHAR(100) NOT NULL,
    annotation     VARCHAR(500) NOT NULL
);

CREATE TABLE specimens
(
    specimen_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    program_id    BIGINT       NOT NULL REFERENCES programs,
    marking       VARCHAR(100) NOT NULL,
    standard VARCHAR(100) NOT NULL,
    protocol      VARCHAR(50)  NOT NULL,
    strength      FLOAT,
    module        FLOAT
);